/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/auth/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 登录。同一用户名连续输错 5 次锁 15 分钟。 */
    post: operations['login'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/logout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 退出登录。没登录也返回 204。 */
    post: operations['logout'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/session': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 当前会话（是否登录、是否需要首次设置）。 */
    get: operations['session'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/setup': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 首次设置：库里还没有账号时，用设置码创建第一个账号并登录。 */
    post: operations['setup'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/edges': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 列出关系。 */
    get: operations['list_edges'];
    put?: never;
    /** 新建关系。 */
    post: operations['create_edge'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/edges/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** 删除关系。 */
    delete: operations['delete_edge'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/files': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 上传图片（请求体就是文件本身，`Content-Type` 写图片类型）。内容相同的文件只存一份。 */
    post: operations['upload_file'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/files/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 读取文件。 */
    get: operations['get_file'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 健康检查：数据库可用时返回 200。 */
    get: operations['health'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/nodes': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 列出节点（最近更新的在前）。 */
    get: operations['list_nodes'];
    put?: never;
    /** 新建节点。 */
    post: operations['create_node'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/nodes/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 读取一个节点。 */
    get: operations['get_node'];
    put?: never;
    post?: never;
    /** 删除节点及其关系。痕迹保留。 */
    delete: operations['delete_node'];
    options?: never;
    head?: never;
    /** 修改节点（只改给出的字段）。 */
    patch: operations['update_node'];
    trace?: never;
  };
  '/api/nodes/{id}/children': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 按顺序列出子节点（一页里的各块）。 */
    get: operations['list_children'];
    /** 重排子节点：给出现有子节点的新顺序。 */
    put: operations['reorder_children'];
    /** 在指定位置插入一个或多个新的子节点，返回新建的节点。 */
    post: operations['create_children'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/nodes/{id}/shares': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 一个节点上的分享链接（含已作废的）。 */
    get: operations['list_shares'];
    put?: never;
    /** 给一个节点开一条分享链接。 */
    post: operations['create_share'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/nodes/{id}/traces': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 节点的痕迹（谁、何时、做了什么）。 */
    get: operations['list_node_traces'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/share/{token}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 读一张草图：返回整理好的文字说明。**不用登录**。 */
    get: operations['read_share'];
    /** 用新画面替换。**不用登录**，但只有 write 链接可以。 */
    put: operations['write_share'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/share/{token}/files/{file}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 画面里用到的附件（原图，不压缩）。不用登录。 */
    get: operations['share_file'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/share/{token}/png': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 整张图的图片。不用登录。 */
    get: operations['share_image'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/share/{token}/scene.json': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 画布的原始数据。不用登录。 */
    get: operations['share_scene'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/shares/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** 作废一条分享链接。 */
    delete: operations['revoke_share'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** @description 谁做的。规则 2：AI 和处理器只提议，人裁决——所以永远要分得清是谁写的。 */
    Actor:
      | {
          id?: components['schemas']['UserId'] | null;
          /** @enum {string} */
          type: 'user';
        }
      | {
          id: string;
          /** @enum {string} */
          type: 'processor';
          version: string;
        };
    /** @description 关系：两个节点之间有类型、有方向的连接。 */
    Edge: {
      /** Format: date-time */
      created_at: string;
      id: components['schemas']['EdgeId'];
      /** @description 关系类型键，例如 `related`。以后关系类型本身也会成为节点。 */
      kind: string;
      source: components['schemas']['NodeId'];
      target: components['schemas']['NodeId'];
    };
    /**
     * Format: uuid
     * @description 关系 ID。
     */
    EdgeId: string;
    /** @description 所有接口统一的错误格式。 */
    ErrorBody: {
      /**
       * @description 机器可读：`invalid`、`unauthorized`（没登录）、`forbidden`、`not_found`、`conflict`、
       *     `locked`（输错太多次）、`internal`。
       */
      error: string;
      message: string;
    };
    FileRef: {
      /** Format: uuid */
      id: string;
      /** @description 在 Markdown 里引用用的地址，例如 `![](/api/files/…)`。 */
      url: string;
    };
    Health: {
      /** @description 构建时的 git commit（镜像里由 CI 写入 `XENICA_COMMIT`），本地开发时为空。 */
      commit?: string | null;
      status: string;
      version: string;
    };
    Login: {
      name: string;
      password: string;
    };
    /** @description 在某个节点里按顺序插入新的子节点（一次可以插多个，例如粘贴一整段笔记）。 */
    NewChildren: {
      /**
       * Format: int32
       * @description 插到第几个位置（从 0 开始）；省略时放到最后。
       */
      index?: number | null;
      nodes: components['schemas']['NewNode'][];
    };
    NewEdge: {
      /** @description 省略时为 `related`。 */
      kind?: string | null;
      source: components['schemas']['NodeId'];
      target: components['schemas']['NodeId'];
    };
    /** @description 新建节点的输入。 */
    NewNode: {
      /** @description 约定：文字内容放在 `md`（Markdown），其中的 `#标记` 和 `[[名字]]` 会自动连到同名节点。 */
      body?: Record<string, never> | null;
      /**
       * Format: uuid
       * @description 客户端可以自己生成 ID（UUID v7），这样不用等服务器就能接着编辑。省略时由服务器生成。
       */
      id?: string | null;
      /** @description 省略时为 `note`。 */
      kind?: string | null;
      /** @description 可省略。 */
      title?: string;
    };
    NewShare: {
      /** @description `read`（给 AI 读）或 `write`（给 AI 改）。 */
      mode: components['schemas']['ShareMode'];
    };
    /** @description 节点：一切有身份的东西（知识点、文件、任务、设置……）。 */
    Node: {
      /** @description 节点内容。结构由类型决定，核心不解释它。 */
      body: Record<string, never>;
      /** Format: date-time */
      created_at: string;
      id: components['schemas']['NodeId'];
      /** @description 类型键，例如 `note`。以后类型本身也会成为节点，这里先用字符串。 */
      kind: string;
      /** @description 可以为空：没有标题时界面用正文第一行代替。 */
      title: string;
      /** Format: date-time */
      updated_at: string;
    };
    /**
     * Format: uuid
     * @description 节点 ID。身份只看 ID，不看名字。
     */
    NodeId: string;
    /** @description 修改节点的输入。只改给出的字段。 */
    NodePatch: {
      body?: Record<string, never> | null;
      title?: string | null;
    };
    SceneInput: {
      /** @description Excalidraw 的画面数据，原样存下来。 */
      scene: unknown;
    };
    Session: {
      /** @description 示例数据模式（预览站）：可以用 `demo` / `demo` 登录。 */
      demo: boolean;
      /** @description 还没有任何账号：界面显示「创建账号」，需要服务日志里的设置码。 */
      setup_required: boolean;
      user?: components['schemas']['User'] | null;
    };
    Setup: {
      /** @description 服务启动时打印在日志里的一次性设置码。 */
      code: string;
      name: string;
      password: string;
    };
    /** @description 一条分享链接（带好可以直接用的地址）。 */
    ShareBody: {
      /** Format: date-time */
      created_at: string;
      /** Format: uuid */
      id: string;
      /** @description 画面图片。 */
      image: string;
      mode: components['schemas']['ShareMode'];
      /** Format: uuid */
      node: string;
      /** Format: date-time */
      revoked_at?: string | null;
      token: string;
      /** @description 交给 AI 的地址：打开就是文字说明；write 链接也用这个地址改画面。 */
      url: string;
    };
    /**
     * @description 分享链接的用法。决定拿到这个地址的人能做什么。
     * @enum {string}
     */
    ShareMode: 'read' | 'write';
    /** @description 痕迹：只增不改的事件记录（数据库触发器保证不能改、不能删）。 */
    Trace: {
      /** @description 例如 `node.created`、`edge.deleted`。 */
      action: string;
      actor: components['schemas']['Actor'];
      /** Format: date-time */
      at: string;
      detail: Record<string, never>;
      id: components['schemas']['TraceId'];
      /**
       * Format: uuid
       * @description 被操作的节点或关系的 ID。
       */
      subject: string;
    };
    /**
     * Format: uuid
     * @description 痕迹 ID。
     */
    TraceId: string;
    /** @description 账号。密码哈希不在这里：它只存在 store 里，永远不出现在接口上（规则 9）。 */
    User: {
      /** Format: date-time */
      created_at: string;
      id: components['schemas']['UserId'];
      name: string;
    };
    /**
     * Format: uuid
     * @description 账号 ID。
     */
    UserId: string;
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  login: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['Login'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['User'];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  logout: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  session: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Session'];
        };
      };
    };
  };
  setup: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['Setup'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['User'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  list_edges: {
    parameters: {
      query?: {
        /** @description 只返回与这个节点相连的关系。 */
        node?: components['schemas']['NodeId'];
        /** @description 默认 2000，上限 5000。 */
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Edge'][];
        };
      };
    };
  };
  create_edge: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['NewEdge'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Edge'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  delete_edge: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  upload_file: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'image/*': number[];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FileRef'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  get_file: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'image/*': number[];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  health: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Health'];
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  list_nodes: {
    parameters: {
      query?: {
        /** @description 最多返回多少条，默认 200，上限 1000。 */
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Node'][];
        };
      };
    };
  };
  create_node: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['NewNode'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Node'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  get_node: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Node'];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  delete_node: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  update_node: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['NodePatch'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Node'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  list_children: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Node'][];
        };
      };
    };
  };
  reorder_children: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': string[];
      };
    };
    responses: {
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  create_children: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['NewChildren'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Node'][];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  list_shares: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ShareBody'][];
        };
      };
    };
  };
  create_share: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['NewShare'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ShareBody'];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  list_node_traces: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Trace'][];
        };
      };
    };
  };
  read_share: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        token: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'text/markdown': string;
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  write_share: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        token: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SceneInput'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Node'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  share_file: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        token: string;
        file: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'image/*': number[];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  share_image: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        token: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'image/png': number[];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  share_scene: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        token: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  revoke_share: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
}
