<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>MetaDump</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.Reflection.Metadata" Version="8.0.0" />
    <PackageReference Include="dnlib" Version="4.5.0" />
  </ItemGroup>
</Project>
